### PR TITLE
fix HSBXL description

### PR DESCRIPTION
**Pull request by zoobab**
fix HSBXL description

### CODE REVIEW

**Comment by warddr** [comment]
This pull request is based on an old version of this repository and can not be merged as is. Can you update your repository so it can be merged?

**Comment by betz** [comment]
my latest merge made this one obsolete. 
MR can be removed

**Comment by zoobab** [comment]
2 years to merge a commit?

**Comment by betz** [comment]
Mine was merged in a few hours.
But it made this MR unnecessary

**Pull request closed without merging**
